# Day 1: NumPy Fundamentals

Welcome to your first day of Scientific Python! Today's goal is to get comfortable with the basics of NumPy, the foundational package for numerical computing in Python.

As always, start by importing NumPy.

In [4]:
import numpy as np

---

## Part 1: Creating NumPy Arrays

In this section, you'll practice creating NumPy arrays in various ways.

**Exercise 1.1:** Create a 1-dimensional NumPy array from the following Python list:
```python
my_list = [1, 2, 3, 4, 5]
```

In [2]:
# Your code here
list = [1, 2, 3, 4, 5, 6]
array = np.array(list)
print(array)

[1 2 3 4 5 6]


**Solution 1.1:**

In [3]:
# Solution
my_list = [1, 2, 3, 4, 5]
array_1d = np.array(my_list)
print(array_1d)

[1 2 3 4 5]


**Exercise 1.2:** Create a 2-dimensional NumPy array (a 2x3 matrix) from the following nested list:
```python
nested_list = [[1, 2, 3], [4, 5, 6]]
```

In [5]:
# Your code here
nested_list = [[1, 2, 3], [4, 5, 6]]
array2x3 = np.array(nested_list)
print(array2x3)

[[1 2 3]
 [4 5 6]]


**Solution 1.2:**

In [ ]:
# Solution
nested_list = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(nested_list)
print(array_2d)

**Exercise 1.3:** Create a 3x4 NumPy array filled with zeros.

In [6]:
# Your code here
array0 = np.zeros((3,4))
print(array0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Solution 1.3:**

In [ ]:
# Solution
zeros_array = np.zeros((3, 4))
print(zeros_array)

**Exercise 1.4**: Create a 2x5 NumPy array filled with ones, and make sure the data type is integer.

In [ ]:
# Your code here

**Solution 1.4:**

In [ ]:
# Solution
ones_array = np.ones((2, 5), dtype=int)
print(ones_array)

**Exercise 1.5**: Create a NumPy array containing numbers from 10 to 25 (inclusive).

In [ ]:
# Your code here

**Solution 1.5:**

In [ ]:
# Solution
range_array = np.arange(10, 26)
print(range_array)

---

## Part 2: Array Arithmetic

Now, let's perform some basic mathematical operations.

First, create these two arrays to work with:

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

**Exercise 2.1:** Add array `a` and array `b` together.

In [ ]:
# Your code here

**Solution 2.1:**

In [ ]:
# Solution
sum_array = a + b
print(sum_array)

**Exercise 2.2:** Multiply array `a` by a scalar value of 5.

In [ ]:
# Your code here

**Solution 2.2:**

In [ ]:
# Solution
scalar_mult_array = a * 5
print(scalar_mult_array)

**Exercise 2.3:** Calculate the element-wise product of `a` and `b`.

In [ ]:
# Your code here

**Solution 2.3:**

In [ ]:
# Solution
element_product = a * b
print(element_product)

**Exercise 2.4:** Subtract array `a` from `b`.

In [ ]:
# Your code here

**Solution 2.4:**

In [ ]:
# Solution
diff_array = b - a
print(diff_array)

---

## Part 3: Basic Statistical Operations

NumPy makes it easy to perform statistical calculations. Let's use the Iris dataset to practice this.

First, let's extract the sepal length column into a NumPy array. The sepal length is the first column in the `iris_data.data`.

In [ ]:
from sklearn.datasets import load_iris
iris_data = load_iris()

# This selects all rows and the first column (index 0)
sepal_length = iris_data.data[:, 0]

**Exercise 3.1:** Calculate the mean (average) sepal length.

In [ ]:
# Your code here

**Solution 3.1:**

In [ ]:
# Solution
mean_sepal_length = np.mean(sepal_length)
print(f"Mean sepal length: {mean_sepal_length}")

**Exercise 3.2:** Calculate the median sepal length.

In [ ]:
# Your code here

**Solution 3.2:**

In [ ]:
# Solution
median_sepal_length = np.median(sepal_length)
print(f"Median sepal length: {median_sepal_length}")

**Exercise 3.3:** Calculate the standard deviation of the sepal length.

In [ ]:
# Your code here

**Solution 3.3:**

In [ ]:
# Solution
std_sepal_length = np.std(sepal_length)
print(f"Standard deviation of sepal length: {std_sepal_length}")

**Exercise 3.4:** Find the minimum and maximum sepal length values.

In [ ]:
# Your code here

**Solution 3.4:**

In [ ]:
# Solution
min_sepal_length = np.min(sepal_length)
max_sepal_length = np.max(sepal_length)
print(f"Minimum sepal length: {min_sepal_length}")
print(f"Maximum sepal length: {max_sepal_length}")

**Bonus Exercise:** For the entire `iris_data.data` array, calculate the mean of each *feature* (i.e., the mean of each column).

*Hint: Look up the `axis` parameter in NumPy functions.*

In [ ]:
# Your code here

**Solution Bonus Exercise:**

In [ ]:
# Solution
mean_per_feature = np.mean(iris_data.data, axis=0)
print("Mean of each feature (column):")
print(mean_per_feature)

---

Great job completing Day 1! Tomorrow, you'll dive into more advanced NumPy topics like indexing, slicing, and reshaping arrays.