# Day 2: NumPy Array Manipulation

Today, you'll dive deeper into NumPy's power by learning how to select, modify, and reshape data within arrays. These skills are crucial for data preprocessing and analysis.

We will cover three main topics:
1.  **Indexing and Slicing 1D Arrays**
2.  **Indexing and Slicing 2D Arrays**
3.  **Reshaping and Combining Arrays**

As always, start by importing NumPy.

In [1]:
import numpy as np

---

## Part 1: Indexing and Slicing 1D Arrays

These exercises focus on accessing and modifying elements in one-dimensional arrays.

First, create the following array to work with:

In [17]:
arr_1d = np.arange(10, 26)
print(f"Original array: {arr_1d}")

Original array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


**Exercise 1.1:** Access the first element of `arr_1d`.

In [3]:
# Your code here
print(arr_1d[0])

10


**Solution 1.1:**

In [4]:
# Solution
first_element = arr_1d[0]
print(f"First element: {first_element}")

First element: 10


**Exercise 1.2:** Access the last element of `arr_1d` using negative indexing.

In [5]:
# Your code here
print(arr_1d[-1])

25


**Solution 1.2:**

In [6]:
# Solution
last_element = arr_1d[-1]
print(f"Last element: {last_element}")

Last element: 25


**Exercise 1.3:** "Slice" the array to get the elements from index 2 up to (but not including) index 7.

In [7]:
# Your code here
print(arr_1d[2:7])

[12 13 14 15 16]


**Solution 1.3:**

In [8]:
# Solution
sliced_array = arr_1d[2:7]
print(f"Sliced array: {sliced_array}")

Sliced array: [12 13 14 15 16]


**Exercise 1.4:** Get the last 5 elements of `arr_1d`.

In [13]:
# Your code here
print(arr_1d[-5:])

[21 22 23 24 25]


**Solution 1.4:**

In [12]:
# Solution
last_five = arr_1d[-5:]
print(f"Last 5 elements: {last_five}")

Last 5 elements: [21 22 23 24 25]


**Exercise 1.5:** Modify the element at index 5 to be `99`.

In [18]:
# Your code here
arr_1d[5] = 99
print(arr_1d)

[10 11 12 13 14 99 16 17 18 19 20 21 22 23 24 25]


**Solution 1.5:**

In [16]:
# Solution
arr_1d[5] = 99
print(f"Modified array: {arr_1d}")

Modified array: [10 11 12 13 99 99 16 17 18 19 20 21 22 23 24 25]


---

## Part 2: Indexing and Slicing 2D Arrays

Now let's work with two-dimensional arrays (matrices).

Create this 2D array for the following exercises:

In [19]:
arr_2d = np.array([[10, 11, 12, 13],
                   [20, 21, 22, 23],
                   [30, 31, 32, 33],
                   [40, 41, 42, 43]])
print("Original 2D array:\n", arr_2d)

Original 2D array:
 [[10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


**Exercise 2.1:** Access the element in the 2nd row and 3rd column (the value `22`).

In [23]:
# Your code here
print(f"The element in the 2nd row and 3rd column is: {arr_2d[1,2]}")

The element in the 2nd row and 3rd column is: 22


**Solution 2.1:**

In [24]:
# Solution
element_22 = arr_2d[1, 2] # Remember, indexing starts at 0!
print(f"Element at (1, 2) is: {element_22}")

Element at (1, 2) is: 22


**Exercise 2.2:** Slice the array to get the top-right 2x2 sub-matrix. (i.e., `[[12, 13], [22, 23]]`).

In [25]:
# Your code here
print(arr_2d[0:2, 2:4])

[[12 13]
 [22 23]]


**Solution 2.2:**

In [ ]:
# Solution
top_right_2x2 = arr_2d[:2, 2:]
print("Top-right 2x2 matrix:\n", top_right_2x2)

Top-right 2x2 matrix:
 [[12 13]
 [22 23]]


**Exercise 2.3:** Get the entire 3rd row (the one starting with `30`).

In [27]:
# Your code here
print(arr_2d[2])

[30 31 32 33]


**Solution 2.3:**

In [28]:
# Solution
third_row = arr_2d[2, :] # or simply arr_2d[2]
print(f"Third row: {third_row}")

Third row: [30 31 32 33]


**Exercise 2.4 (Challenge):** Select all elements in the array that are greater than 30. This is called boolean indexing.

In [30]:
# Your code here
print(arr_2d[arr_2d > 30])

[31 32 33 40 41 42 43]


**Solution 2.4:**

In [31]:
# Solution
greater_than_30 = arr_2d[arr_2d > 30]
print(f"Elements greater than 30: {greater_than_30}")

Elements greater than 30: [31 32 33 40 41 42 43]


---

## Part 3: Reshaping and Combining Arrays

Finally, let's look at changing the shape of arrays and putting them together.

**Exercise 3.1:** Create a 1D array with 12 elements, from 0 to 11. Then, reshape it into a 3x4 matrix.

In [37]:
# Your code here
arr = np.arange(0, 12)
reshaped_arr = arr.reshape(3,4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Solution 3.1:**

In [38]:
# Solution
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print("Reshaped 3x4 matrix:\n", reshaped_arr)

Reshaped 3x4 matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Exercise 3.2:** Using the `reshaped_arr` from the previous exercise, get its transpose. The transpose swaps rows and columns.

In [39]:
# Your code here
print(reshaped_arr.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**Solution 3.2:**

In [40]:
# Solution
transposed_arr = reshaped_arr.T
print("Transposed matrix:\n", transposed_arr)

Transposed matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**Exercise 3.3:** Create two arrays, `a1` and `a2`. Concatenate them vertically (stacking `a2` below `a1`).

In [42]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6]])

# Your code here
print(np.concatenate((a1, a2)))

[[1 2]
 [3 4]
 [5 6]]


**Solution 3.3:**

In [ ]:
# Solution
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6]])
vertical_stack = np.vstack((a1, a2))
# Alternative: np.concatenate((a2, a2), axis=0)
print("Vertical concatenation:\n", vertical_stack)

Vertical concatenation:
 [[1 2]
 [3 4]
 [5 6]]


**Exercise 3.4:** Now, concatenate `a1` and a new array `a3` horizontally.

In [48]:
a1 = np.array([[1, 2], [3, 4]])
a3 = np.array([[5], [6]]) # Note the shape of a3

# Your code here
print(np.concatenate((a1, a3), axis = 1))

[[1 2 5]
 [3 4 6]]


**Solution 3.4:**

In [49]:
# Solution
a1 = np.array([[1, 2], [3, 4]])
a3 = np.array([[5], [6]])
horizontal_stack = np.hstack((a1, a3))
# Alternative: np.concatenate((a1, a3), axis=1)
print("Horizontal concatenation:\n", horizontal_stack)

Horizontal concatenation:
 [[1 2 5]
 [3 4 6]]


---

### Excellent progress!

You've now covered some of the most common and important array manipulation techniques in NumPy. These skills will be incredibly useful when you start cleaning and preparing data with Pandas. Keep up the great work!